name: Android Release
on: 
    push: 
        branches: [main]
    pull_request: 
        branches: [main]
    workflow_dispatch: 
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.1
            - uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: '17'
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
            - name: Get dependencies
              run: flutter pub get
            - run: flutter test --coverage
            - run: flutter analyze
            - run: flutter build apk --relase